//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.NewHireOnboarding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.NewHireOnboarding.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * New employee checklist - Type this to view your New employee checklist.
        /// </summary>
        public static string AccessOnDemandBulletPoint {
            get {
                return ResourceManager.GetString("AccessOnDemandBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is not available.
        /// </summary>
        public static string AlternativeText {
            get {
                return ResourceManager.GetString("AlternativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ApproveButtonText {
            get {
                return ResourceManager.GetString("ApproveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your introduction is approved by your manager. Soon, he&apos;ll share it with the team..
        /// </summary>
        public static string ApprovedMessageText {
            get {
                return ResourceManager.GetString("ApprovedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee Onboarding.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on to view complete on boarding plan..
        /// </summary>
        public static string BoardingCheckListHeaderText {
            get {
                return ResourceManager.GetString("BoardingCheckListHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your introduction couldn&apos;t be posted. You must first add the bot to a team where you&apos;re a member..
        /// </summary>
        public static string BotNotInstalledInTeamMessageText {
            get {
                return ResourceManager.GetString("BotNotInstalledInTeamMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We value your feedback. How is onboarding going for you?.
        /// </summary>
        public static string CardContentText {
            get {
                return ResourceManager.GetString("CardContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee survey.
        /// </summary>
        public static string CardHeaderText {
            get {
                return ResourceManager.GetString("CardHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help make the new hire experience even better!.
        /// </summary>
        public static string CardSubHeaderText {
            get {
                return ResourceManager.GetString("CardSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        public static string ChatButtonText {
            get {
                return ResourceManager.GetString("ChatButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        public static string ChatWithMatchButtonText {
            get {
                return ResourceManager.GetString("ChatWithMatchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your comments (200 characters max.).
        /// </summary>
        public static string CommentsPlaceHolderText {
            get {
                return ResourceManager.GetString("CommentsPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your complete plan is not available right now..
        /// </summary>
        public static string CompleteLearningPlanNotExistText {
            get {
                return ResourceManager.GetString("CompleteLearningPlanNotExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning plan is not available for this week..
        /// </summary>
        public static string CurrentWeekLearningPlanNotExistText {
            get {
                return ResourceManager.GetString("CurrentWeekLearningPlanNotExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit intro.
        /// </summary>
        public static string EditIntroButtonText {
            get {
                return ResourceManager.GetString("EditIntroButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there! Have a look!.
        /// </summary>
        public static string EditIntroCardHeaderText {
            get {
                return ResourceManager.GetString("EditIntroCardHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manager would you to update your introduction..
        /// </summary>
        public static string EditIntroCardSubHeaderText {
            get {
                return ResourceManager.GetString("EditIntroCardSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when I tried to handle your request. Bot is unable to update user details right now. Try again in a few minutes..
        /// </summary>
        public static string ErrorInUpdatingUserChoice {
            get {
                return ResourceManager.GetString("ErrorInUpdatingUserChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **We would love to hear from you!**.
        /// </summary>
        public static string FeedbackHeaderText {
            get {
                return ResourceManager.GetString("FeedbackHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your feedback.
        /// </summary>
        public static string FeedbackPlaceHolderText {
            get {
                return ResourceManager.GetString("FeedbackPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view or download your report,  go to the Feedback tab in this channel..
        /// </summary>
        public static string FeedbackReportNavigationText {
            get {
                return ResourceManager.GetString("FeedbackReportNavigationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback can&apos;t be empty. Try again..
        /// </summary>
        public static string FeedbackRequiredFieldText {
            get {
                return ResourceManager.GetString("FeedbackRequiredFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your feedback. I&apos;ll share it with onboarding team..
        /// </summary>
        public static string FeedbackSuccessMessageText {
            get {
                return ResourceManager.GetString("FeedbackSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackTitleText {
            get {
                return ResourceManager.GetString("FeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reach app. Please try again in a few minutes..
        /// </summary>
        public static string GenericErrorMessageText {
            get {
                return ResourceManager.GetString("GenericErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take survey.
        /// </summary>
        public static string GetStartedButtonText {
            get {
                return ResourceManager.GetString("GetStartedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Share feedback - Type this to share thoughts on improving the NEO experience.
        /// </summary>
        public static string HelpBulletPoint {
            get {
                return ResourceManager.GetString("HelpBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know that command. Take a tour to learn the commands you can type and what they do..
        /// </summary>
        public static string HelpCardHeaderText {
            get {
                return ResourceManager.GetString("HelpCardHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Review introductions - Type this to review new employee intros.
        /// </summary>
        public static string HiringManagerBulletPoint1Text {
            get {
                return ResourceManager.GetString("HiringManagerBulletPoint1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Share feedback - Type this to share thoughts on improving the NEO experience.
        /// </summary>
        public static string HiringManagerBulletPoint2Text {
            get {
                return ResourceManager.GetString("HiringManagerBulletPoint2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I help managers approve employee intros and distribute onboarding plans. Also, I respond to the following commands:.
        /// </summary>
        public static string HiringManagerWelcomeContentText {
            get {
                return ResourceManager.GetString("HiringManagerWelcomeContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * View/download feedback.
        /// </summary>
        public static string HumanResourceBulletPointText {
            get {
                return ResourceManager.GetString("HumanResourceBulletPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I help new employees onboard and ramp up quickly. Then, I collect feedback to share with the HR team on how the onboarding experience can be improved. I will send you a monthly feedback report..
        /// </summary>
        public static string HumanResourceWelcomeContentText {
            get {
                return ResourceManager.GetString("HumanResourceWelcomeContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there,.
        /// </summary>
        public static string InitiateChatText {
            get {
                return ResourceManager.GetString("InitiateChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce yourself.
        /// </summary>
        public static string IntroduceButtonText {
            get {
                return ResourceManager.GetString("IntroduceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us a little about yourself. Once approved by your manager, I&apos;ll share your intro with your team..
        /// </summary>
        public static string IntroductionBriefText {
            get {
                return ResourceManager.GetString("IntroductionBriefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi all, {0} here, happy to join as a part of the team. I don&apos;t really know what to say though. Please reach out to me if you have any question.:).
        /// </summary>
        public static string IntroductionGreetText {
            get {
                return ResourceManager.GetString("IntroductionGreetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string IntroductionHeaderText {
            get {
                return ResourceManager.GetString("IntroductionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a brief intro (500 characters max.).
        /// </summary>
        public static string IntroductionInputPlaceholderText {
            get {
                return ResourceManager.GetString("IntroductionInputPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string IntroductionSubmitButtonText {
            get {
                return ResourceManager.GetString("IntroductionSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! we strive to create strong teams and an inclusive environment. The first step is helping our employees know one another. Take a moment to tell us about yourself. We&apos;ll share this info with the team..
        /// </summary>
        public static string IntroductionText {
            get {
                return ResourceManager.GetString("IntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce yourself.
        /// </summary>
        public static string IntroductionTitle {
            get {
                return ResourceManager.GetString("IntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks so much! I&apos;ve shared your intro with your manager. I&apos;ll let you know if anything else is needed..
        /// </summary>
        public static string IntroSubmittedMessage {
            get {
                return ResourceManager.GetString("IntroSubmittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid tenant..
        /// </summary>
        public static string InvalidTenantText {
            get {
                return ResourceManager.GetString("InvalidTenantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an overview of what you&apos;ll learn as a new hire..
        /// </summary>
        public static string LearningPlanBriefText {
            get {
                return ResourceManager.GetString("LearningPlanBriefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share feedback.
        /// </summary>
        public static string LearningPlanShareFeedbackButtonText {
            get {
                return ResourceManager.GetString("LearningPlanShareFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} plan.
        /// </summary>
        public static string LearningPlanWeekListCardTitleText {
            get {
                return ResourceManager.GetString("LearningPlanWeekListCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already approved this introduction..
        /// </summary>
        public static string ManagerApprovalValidationText {
            get {
                return ResourceManager.GetString("ManagerApprovalValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager&apos;s comments:.
        /// </summary>
        public static string ManagerCommentsTitleText {
            get {
                return ResourceManager.GetString("ManagerCommentsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manager hasn&apos;t added the NEO bot and didn&apos;t receive your intro. Please let your manager know..
        /// </summary>
        public static string ManagerUnavailableText {
            get {
                return ResourceManager.GetString("ManagerUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there again, I&apos;m {0}. A bot that pairs you with a new coworker to meet each week. This week your match is {1}.
        /// </summary>
        public static string MatchUpCardContentPart1 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;ve got the inclination, set something up. See, meeting people *is* easy!.
        /// </summary>
        public static string MatchUpCardContentPart2 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been matched with {0}..
        /// </summary>
        public static string MatchUpCardMatchedText {
            get {
                return ResourceManager.GetString("MatchUpCardMatchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time for a match!.
        /// </summary>
        public static string MatchUpCardTitleContent {
            get {
                return ResourceManager.GetString("MatchUpCardTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there, looks like we&apos;ve been matched by {0} this week. It&apos;d be great to meet up for a coffee or a lunch or a call if you&apos;ve got time..
        /// </summary>
        public static string MeetupContent {
            get {
                return ResourceManager.GetString("MeetupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} Meet up.
        /// </summary>
        public static string MeetupTitle {
            get {
                return ResourceManager.GetString("MeetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started now by introducing yourself:.
        /// </summary>
        public static string MoreInfoBulletPoint {
            get {
                return ResourceManager.GetString("MoreInfoBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please explain what you&apos;d like to see updated. I will send your comments to {0}..
        /// </summary>
        public static string MoreInfoCardSubHeaderText {
            get {
                return ResourceManager.GetString("MoreInfoCardSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee intros.
        /// </summary>
        public static string NewEmployeeTitleText {
            get {
                return ResourceManager.GetString("NewEmployeeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A learning plan is not available this week. Check in with your manager for more information..
        /// </summary>
        public static string NoCurrentWeekPlanText {
            get {
                return ResourceManager.GetString("NoCurrentWeekPlanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no intros for you to review right now..
        /// </summary>
        public static string NoPendingIntroductionText {
            get {
                return ResourceManager.GetString("NoPendingIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi everyone! Please welcome {0} to our team!.
        /// </summary>
        public static string NotificationContentText {
            get {
                return ResourceManager.GetString("NotificationContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To submit your introduction, you’ll need to sign in..
        /// </summary>
        public static string NotLoginText {
            get {
                return ResourceManager.GetString("NotLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee checklist.
        /// </summary>
        public static string OnBoardingCheckListText {
            get {
                return ResourceManager.GetString("OnBoardingCheckListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee checklist.
        /// </summary>
        public static string OnBoardingCheckListTitle {
            get {
                return ResourceManager.GetString("OnBoardingCheckListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All set. I&apos;ve resumed your matches. You can turn them off whenever you like..
        /// </summary>
        public static string PausedMatchesCardContent {
            get {
                return ResourceManager.GetString("PausedMatchesCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all matches.
        /// </summary>
        public static string PauseMatchesButtonText {
            get {
                return ResourceManager.GetString("PauseMatchesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. Your intro is pending approval from your manager..
        /// </summary>
        public static string PendingMessageText {
            get {
                return ResourceManager.GetString("PendingMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post in channel.
        /// </summary>
        public static string PostInTeamButtonText {
            get {
                return ResourceManager.GetString("PostInTeamButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose meetup.
        /// </summary>
        public static string ProposeMeetupButtonText {
            get {
                return ResourceManager.GetString("ProposeMeetupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for more details has been sent to the employee..
        /// </summary>
        public static string RequestMoreInfoNotificationText {
            get {
                return ResourceManager.GetString("RequestMoreInfoNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestmoreinfo.
        /// </summary>
        public static string RequestMoreInfoText {
            get {
                return ResourceManager.GetString("RequestMoreInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Required.
        /// </summary>
        public static string RequiredFieldText {
            get {
                return ResourceManager.GetString("RequiredFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume matches.
        /// </summary>
        public static string ResumeMatchesButtonText {
            get {
                return ResourceManager.GetString("ResumeMatchesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve paused your matches. You can resume them at any time..
        /// </summary>
        public static string ResumeMatchesCardContent {
            get {
                return ResourceManager.GetString("ResumeMatchesCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review introduction.
        /// </summary>
        public static string ReviewIntroductionCommandText {
            get {
                return ResourceManager.GetString("ReviewIntroductionCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New hire name can&apos;t be empty. Try again..
        /// </summary>
        public static string ReviewIntroductionInvalidCommandText {
            get {
                return ResourceManager.GetString("ReviewIntroductionInvalidCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a manager, you can approve employee intros before they&apos;re posted in the channel..
        /// </summary>
        public static string ReviewIntroductionsBriefText {
            get {
                return ResourceManager.GetString("ReviewIntroductionsBriefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review introductions.
        /// </summary>
        public static string ReviewIntroductionsText {
            get {
                return ResourceManager.GetString("ReviewIntroductionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review introductions.
        /// </summary>
        public static string ReviewIntroductionText {
            get {
                return ResourceManager.GetString("ReviewIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review introductions.
        /// </summary>
        public static string ReviewIntroductionTitle {
            get {
                return ResourceManager.GetString("ReviewIntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more details.
        /// </summary>
        public static string SeeMoreDetailsButtonText {
            get {
                return ResourceManager.GetString("SeeMoreDetailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendButtonText {
            get {
                return ResourceManager.GetString("SendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share feedback on the onboarding experience so we can make it even better for future hires..
        /// </summary>
        public static string ShareFeedbackBriefText {
            get {
                return ResourceManager.GetString("ShareFeedbackBriefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share feedback.
        /// </summary>
        public static string ShareFeedbackButtonText {
            get {
                return ResourceManager.GetString("ShareFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share feedback.
        /// </summary>
        public static string ShareFeedbackText {
            get {
                return ResourceManager.GetString("ShareFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share feedback.
        /// </summary>
        public static string ShareFeedbackTitle {
            get {
                return ResourceManager.GetString("ShareFeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign In.
        /// </summary>
        public static string SignInHeaderText {
            get {
                return ResourceManager.GetString("SignInHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been signed out..
        /// </summary>
        public static string SigoutText {
            get {
                return ResourceManager.GetString("SigoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitfeedback.
        /// </summary>
        public static string SubmitFeedbackCommandText {
            get {
                return ResourceManager.GetString("SubmitFeedbackCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro successfully posted in selected channel..
        /// </summary>
        public static string SuccessfulPostedMessage {
            get {
                return ResourceManager.GetString("SuccessfulPostedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour.
        /// </summary>
        public static string TakeaTourButtonText {
            get {
                return ResourceManager.GetString("TakeaTourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! Now, tell me where to post this intro..
        /// </summary>
        public static string TeamConfirmHeaderText {
            get {
                return ResourceManager.GetString("TeamConfirmHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined the team!.
        /// </summary>
        public static string TeamNotificationHeaderText {
            get {
                return ResourceManager.GetString("TeamNotificationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Introduce new employees.
        /// </summary>
        public static string TeamWelcomeCardBulletPointText {
            get {
                return ResourceManager.GetString("TeamWelcomeCardBulletPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I help new hires meet the team and ramp up quickly. Here&apos;s what I&apos;ll do in this channel:.
        /// </summary>
        public static string TeamWelcomeContentText {
            get {
                return ResourceManager.GetString("TeamWelcomeContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request more details.
        /// </summary>
        public static string TellMeMoreButtonText {
            get {
                return ResourceManager.GetString("TellMeMoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments can&apos;t be left empty. Try again..
        /// </summary>
        public static string TellMeMoreInputValidationText {
            get {
                return ResourceManager.GetString("TellMeMoreInputValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know that command..
        /// </summary>
        public static string UnSupportedBotCommand {
            get {
                return ResourceManager.GetString("UnSupportedBotCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not mapped with manager in Graph..
        /// </summary>
        public static string UserNotMappedWithManagerMessageText {
            get {
                return ResourceManager.GetString("UserNotMappedWithManagerMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Make sure you answer all the questions.
        /// </summary>
        public static string ValidationMessageText {
            get {
                return ResourceManager.GetString("ValidationMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee checklist.
        /// </summary>
        public static string ViewCompleteLearningPlanButtonText {
            get {
                return ResourceManager.GetString("ViewCompleteLearningPlanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee checklist.
        /// </summary>
        public static string ViewCompleteLearningPlanTitle {
            get {
                return ResourceManager.GetString("ViewCompleteLearningPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View weekly plan.
        /// </summary>
        public static string ViewLearningButtonText {
            get {
                return ResourceManager.GetString("ViewLearningButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View learning.
        /// </summary>
        public static string ViewLearningPlanButtonText {
            get {
                return ResourceManager.GetString("ViewLearningPlanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learnings.
        /// </summary>
        public static string ViewLearningText {
            get {
                return ResourceManager.GetString("ViewLearningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! You have feedback to review..
        /// </summary>
        public static string ViewReportCardHeaderText {
            get {
                return ResourceManager.GetString("ViewReportCardHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly feedback alert.
        /// </summary>
        public static string ViewReportCardTitleText {
            get {
                return ResourceManager.GetString("ViewReportCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve complied recent feedback from new hires in an excel document for you..
        /// </summary>
        public static string ViewReportUserMessageText {
            get {
                return ResourceManager.GetString("ViewReportUserMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string ViewWeeklyLearningPlanCommandText {
            get {
                return ResourceManager.GetString("ViewWeeklyLearningPlanCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll help you introduce yourself to the team and send you weekly learning plans. And, I&apos;ll respond to the following commands in this chat:.
        /// </summary>
        public static string WelcomeContentText {
            get {
                return ResourceManager.GetString("WelcomeContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Onboarding Assistant.
        /// </summary>
        public static string WelcomeHeaderText {
            get {
                return ResourceManager.GetString("WelcomeHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I&apos;m NEO, the New Employee Onboarding bot..
        /// </summary>
        public static string WelcomeMessageText {
            get {
                return ResourceManager.GetString("WelcomeMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say hello to NEO!.
        /// </summary>
        public static string WelcomeSubHeaderText {
            get {
                return ResourceManager.GetString("WelcomeSubHeaderText", resourceCulture);
            }
        }
    }
}
